struct GrassBladeData
{
	float3 Position;
	float2 Facing;

	float WindStrength;
	float PerBladeHash;
	int GrassType;
	
	float2 ClumpFacing;
	float3 ClumpColor;
	
	float Height;
	float Width;
	float Tilt;
	float Bend;
	float SideCurve;
};

RWStructuredBuffer<float4> OutPositions : register(u0);
RWStructuredBuffer<float4> OutRotations : register(u1);
RWStructuredBuffer<uint> IndirectArgs : register(u2); 

void main(void)
{
	
}
